name: NWChem_Release_Tar

on:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  do_tar:
    runs-on: ubuntu-latest
    steps:
      - name: install pkg
        run: |
          sudo apt-get install -y curl make perl bash bzip2 tar gzip openmpi-bin
      - name: grab script
        run: |
          curl -LJO https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/nwchem/$GITHUB_REF_NAME/contrib/git.nwchem/dotar_release.sh
          chmod +x ./dotar_release.sh
      - name: run script
        run: |
          ./dotar_release.sh
      - name: generate tempdir name
        run: |
          echo "tmpdir_name=temp.$(date +%Y%m%d)" >>  $GITHUB_ENV
      - name: check tempdir
        run: |
          ls -lrt ${{ env.tmpdir_name }}/*tar*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nwchem-tarball
          path: ${{ env.tmpdir_name }}/*tar*
      - name: Release nightly
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: ${{ env.tmpdir_name }}/*tar*
          fail_on_unmatched_files: true
